### ISSUE TITLE
Project seems abandoned

### ISSUE THREAD

**Issue by ablake** [contentful/rich-text-renderer-java#13]
This project is linked to from Contentful's documentation on "Getting started with Rich Text":
https://www.contentful.com/developers/docs/tutorials/general/getting-started-with-rich-text-field-type/

However, the project has never seen a non-snapshot release, hasn't been updated for a long time, and still has a banner reading "THIS REPOSITORY IS IN BETA" at the top of its readme.  This means it's not suitable for a production application, meaning we'll either need to implement Rich Text support ourselves or stick with Markdown.

What does the timeline look like for releasing a stable version of this library?

**Comment by rafalniski** [comment]
Hi @ablake!

We are planning to make this library production ready in a couple of weeks. Stay tuned!
