### ISSUE TITLE
Android: minSdkVersion cannot be smaller than 26

### ISSUE THREAD

**Issue by ablake** [contentful/rich-text-renderer-java#14]
Our application has a minSdkVersion of 21 (Android 5.0, Lollipop).  When we declare a dependency on this library, building the project fails with the error:

Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 26 declared in library [com.github.contentful.rich-text-renderer-java:android:master-SNAPSHOT]

A significant number of our users are on OS versions below 8.0, so raising our minSdkVersion isn't viable.  Could lower OS versions be supported somehow?  For example, perhaps it would be possible to render Rich Text documents to CharSequences of Spannables without the need for API level 26 features, even if rendering native views does require them.

**Comment by D-Fox** [comment]
Any update on this? There is also open pull request to support api 23+
https://github.com/contentful/rich-text-renderer-java/pull/10/commits/0a383c34d61f47ce42cf8a1fea3923f325b1155b

It seems that only reason for min api 26 is usage of "java.util.function.Predicate" in two filter methods. This can be easily replaced (or just by using coreLibraryDesugaring).

Is there any other reason for min api 26? The changes needed to support api 23+ are minimal.

**Comment by rafalniski** [comment]
The PR is merged, now library supports api 23+
