### ISSUE TITLE
CDARichDocument Initialization not from CDAClient

### ISSUE THREAD

**Issue by ignkarman** [contentful/rich-text-renderer-java#15]
Question
---

Is it possible to construct a `CDARichDocument` without fetching the entry via the `CDAClient`?

Our project fetches Contentful data from our server, which communicates w/ Contentful. We would like to be able create a CDARichDocument by passing in our rich text data (from Contentful, through our server) in our Android application. 

After reviewing the JavaDoc for the SDK, it seems that this is not possible. There is an available constructor, but with no parameters, and there are no accessible mutable properties on the constructed `CDARichDocument`. From what I can see, the only way to get a `CDARichDocument` constructed with our data is to use the `CDAClient`.  

Is using the `CDAClient` a requirement for using this rich text renderer?

Thanks in advance for any assistance.

**Comment by rafalniski** [comment]
Hey @ignkarman ,

unfortunately `CDARichDocument` is pretty narrow in implementation. You need to use `CDAClient` in your use case.
