### ISSUE TITLE
Convert Contentful JSON to  HTML

### ISSUE THREAD

**Issue by ajayboseac** [contentful/rich-text-renderer-java#17]
Hi Team,

Apologies for spamming this place. 

I have a use case where I am getting JSON content from our contentful repository as part of an API call. its not a direct integration with contentful so we dont have access to CADEntry Object or CDARichDocument object. All I have is the content in the contentful specific JSON format.  How do I convert this JSON to HTML ? 

I already checked out the java script libraries that contentful provides but since we have to display this over a salesforce application that doesn't really help , we tried importing these libraries into salesforce and salesforce locker service wont let us. So are exploring the possibility of converting the JSON document to HTML from our java service and returning the HTML to salesforce. How do we go about it, using this library?

Regards,
Ajay

**Comment by rafalniski** [comment]
Hey,

this library relies on the Java Contentful SDK directly. So currently, there is no way to convert JSON to HTML without using Contentful Data Model.
