### ISSUE TITLE
Is there any plan to maintain this repo?

### ISSUE THREAD

**Issue by MohamedGamalElsayed** [contentful/rich-text-renderer-java#18]
It seems an abandoned project as it is still in Beta and the latest update happened 2 years ago. Do you have any plan to maintain this? 

I can’t even build the project regarding many `gradle` build errors.
FYI when I tried to import it using `gradle`, it failed -so I can’t even import it. That was using instructions mentioned in `README`.

Another thing, is there any other way to render rich text natively in Android?
Thanks in advance

**Comment by rafalniski** [comment]
Hey,

could you please past here build error?

**Comment by MohamedGamalElsayed** [comment]
Hey,

The most important part is:
> It seems an abandoned project as it is still in Beta and the latest update happened 2 years ago. Do you have any plan to maintain this?

So, can you please let me know? Because almost 1 year ago you mentioned in this [issue](https://github.com/contentful/rich-text-renderer-java/issues/13) that you were planning to make it ready for release in 2 weeks. As you know, big corporations can't depend on Beta projects, that's why I'm asking you :) 

For the build error I get after cloning the repo:
`Gradle sync failed: No variants found for 'android'. Check build files to ensure at least one variant exists.`

For importing the library as mentioned in `README`, I get this build error:
`Could not HEAD 'https://nexus.sam-app.ro/repository/android-snapshots/com/github/contentful/contentful.java/v10.4.1/contentful.java-v10.4.1.pom'. Received status code 400 from server: Repository version policy: SNAPSHOT does not allow version: v10.4.1`

Thanks for your help :)

**Comment by rafalniski** [comment]
Please try with now release - `1.1.0`
