### ISSUE TITLE
Publish a non-snapshot version

### ISSUE THREAD

**Issue by mbyrne00** [contentful/rich-text-renderer-java#19]
Hi - thanks for the lib, but having a snapshot tied to `master` branch seems quite dangerous/flakey for other developers down the track.

Jitpack supports github releases and even branches. Would be nice to have a github release and have a locked version for us to reference. If that's too much hassle then even just use another branch that's frozen for updates and we can use `branch-MASTER`.

**Comment by mbyrne00** [comment]
@Khaledgarbaya - is anyone from contentful actively maintaining this repository? Seems more than just a community-led open source effort since this is based around a commercial offering.

**Comment by rpeng** [comment]
We also would love to have a non-snapshot version for hermetic builds

**Comment by amandasage** [comment]
@rafalniski tagging you in this issue

**Comment by mbyrne00** [comment]
From the contentful team, this is not good enough. You have a paid product with significant fees - a good product that warrants it. On the flipside the community are trying to engage to help you improve your libraries with valid feedback and there is radio silence.

Sure, we can use node and JS libs in frontend and backend node servers, and the engagement on those libraries is much better. Other clients in the enterprise, however, are using Java backends and still need rendering for things like email templates, etc.

When you are selling enterprise plans and not offering clear-cut releases of your libraries it's not good enough. The only activity on this repository since January has been to update README and nobody is providing feedback to the issues raised.

**Comment by mbyrne00** [comment]
Also, the contentful org already has capability to push real maven releases (see https://github.com/contentful/contentful.java). I can't see why this lib can't be doing the same thing. Surely the two teams could help each other given this repository sits under the same github org.

**Comment by amandasage** [comment]
Hi @mbyrne00 I do apologize for the delay on this and I will relay your feedback to our team. We have fewer resources maintaining this SDK (compared to JS lib) and I will do my best to escalate this and keep following up.

**Comment by mbyrne00** [comment]
Thank you @amandasage. Ultimately we would like semver versions published to maven central like https://github.com/contentful/contentful.java but meantime we have an urgent requirement to have a _locked_ version we can refer to as any build using this is a ticking time bomb ... so if someone can quickly create a branch/release/tag that Jitpack can refer to then this would at least give us some safety meantime.

**Comment by amandasage** [comment]
@mbyrne00 no worries I will directly flag #20 as well with our developer and try to get some better traction on this

**Comment by rafalniski** [comment]
@mbyrne00 Right, I will look into that.

**Comment by mbyrne00** [comment]
Hi @rafalniski - confirmed `1.1.0` downloads correctly now and readme is updated. Good to close now. Thanks for your help.
