### ISSUE TITLE
HTML output should escape special characters

### ISSUE THREAD

**Issue by mbyrne00** [contentful/rich-text-renderer-java#20]
XML/HTML chars should be escaped in resulting HTML.

To reproduce:

Rich text field in contentful contains text like:
```
Testing, 123 <something-here>
```

Expected output
```
Testing, 123 &lt;something-here&gt;
```

Actual output:
```
Testing, 123 <something-here>
```

Without escaping these characters, various clients will see this as invalid html. When we use this for sending email, for example, we have seen this content stripped out and we can't see `<something-here>`. Our content editors are non-technical so this is a valid scenario.

Standard replacements 

```
&amp; → & (ampersand, U+0026)
&lt; → < (less-than sign, U+003C)
&gt; → > (greater-than sign, U+003E)
&quot; → " (quotation mark, U+0022)
&apos; → ' (apostrophe, U+0027)
```

**Comment by mbyrne00** [comment]
Hi @rafalniski - still waiting to hear back on this. The comment above explains why we can't do the replacement on our side, because we can't distinguish between `<` and`>` and valid html. I've also flagged this with our corporate support contact. Can you please let us know how we can proceed?

**Comment by mbyrne00** [comment]
Hi @rafalniski - can you please provide a code snippet of how to use the update?

**Comment by mbyrne00** [comment]
Hi @rafalniski - thanks for doing that. I did a small test and it seems to work.

As a bonus, I think in your source code it could benefit from a simple test or few similar to `MarksTest`, `ListsTest`, `LinksTest` etc ... they seem simple to write and illustrate. Not urgent.

Meanwhile it seems to be working as expected, so thank you for the update!

**Comment by rafalniski** [comment]
@mbyrne00 Good point, I added a simple test and fixed others.
