### ISSUE TITLE
Table not being rendered correctly.

### ISSUE THREAD

**Issue by bellam** [contentful/rich-text-renderer-java#27]
A simple table with Two rows and two columns returns the following HTML when a Rich text field is processed.

**HTML Rendered when htmlProcessor.process method is called:**
```
<div>
  <div>
  </div>
  <div>
  </div>
</div>
```

**Content in WYSIWYG editor:**

<img width="764" alt="image" src="https://user-images.githubusercontent.com/1712809/176423090-602ff850-4265-4d20-bef8-3eca00fa82ed.png">

**Comment by rafalniski** [comment]
Rich text tables are not yet supported in the library. There is a plan to work on that in the next iteration. I will keep you posted when it's ready.

**Comment by rafalniski** [comment]
@bellam This is now supported in `1.4.0`
