### ISSUE TITLE
Access denied to jitpack.io

### ISSUE THREAD

**Issue by Irene-GF** [contentful/rich-text-renderer-java#28]
I am having an error when building Maven Project:

Access denied to https://jitpack.io/com/github/contentful/rich/html/1.3.0/html-1.3.0.pom. Error code 401

Can you help me?

Thank you so much.

**Comment by marianoesteban** [comment]
That's probably because the groupId of the html dependency should be `com.github.contentful.rich-text-renderer-java` instead of `com.github.contentful.rich`. There is an error in the README.

**Comment by Irene-GF** [comment]
That was the problem! Thank you so much!

**Comment by rafalniski** [comment]
Thanks for catching that! Fixed the dependency.
