### ISSUE TITLE
No new line between nodes. 

### ISSUE THREAD

**Issue by davramescu** [contentful/rich-text-renderer-java#30]
I tried out the rich text renderer libs for Android and noticed that there are no new lines between nodes. This might have to do with the `childWithNewline` method in the `BlockRenderer`.

Content:

![image001[18].png](https://user-images.githubusercontent.com/6944066/184681556-23fb9d24-c66a-4447-b226-718a8a77911c.png)

Objects:

![image001[37].png](https://user-images.githubusercontent.com/6944066/184681591-24a7825f-a1d1-4ad2-8958-6bee468f0d79.png)

Resulted rendered text:

![image002[30].png](https://user-images.githubusercontent.com/6944066/184681642-d414f6b2-08f2-4e63-a630-0df10978bd2c.png)

**Comment by rafalniski** [comment]
This should be fixed in `1.9.0`. Please reopen if the issue persists.
