### ISSUE TITLE
Add ability to set CDARichDocument/RichText content in renderer initialization

### ISSUE THREAD

**Issue by mchuangatfiskerinc** [contentful/rich-text-renderer-java#38]
This is a feature request for this project as a current Contentful customer.  Our use case is that our mobile apps get the Contentful _RichText_ data from our own company's API (it acts like a proxy in front of Contentful APIs). 

@rafalniski is it possible to expose an Android equivalent function (similar to web renderer) where we are able to set the data for the renderer without an initial network call?  Below is how it is done on the web.

```
const document = {
  nodeType: 'document',
  data: {},
  content: [
    {
      nodeType: 'paragraph',
      data: {},
      content: [
        {
          nodeType: 'text',
          value: 'Hello',
          data: {},
          marks: [{ type: 'bold' }],
        },
        {
          nodeType: 'text',
          value: ' world!',
          data: {},
          marks: [{ type: 'italic' }],
        },
      ],
    },
  ],
};

documentToHtmlString(document, options);
```

Web snippet reference: https://www.contentful.com/developers/docs/javascript/tutorials/rendering-contentful-rich-text-with-javascript/

**Comment by amatkivskiy** [comment]
@rafalniski  I am also interested in this functionality.

**Comment by rafalniski** [comment]
Hey,

I recently added some workaround for this feature, it should work with latest library version. Here is sample code in Java:
```
public class RichTextJSONParser {
   private final Gson gson = new Gson();
   public CDARichDocument parseRichTextDocument(String json) throws Exception {
      Type type = new TypeToken<Map<String, Object>>(){}.getType();
      Map<String, Object> jsonMap = gson.fromJson(json, type);
      return (CDARichDocument) RichTextFactory.resolveRichNode(jsonMap);
   }
}
