### ISSUE TITLE
Extra space in the tag

### ISSUE THREAD

**Issue by IvanVoevodin** [contentful/rich-text-renderer-java#41]
Hi everyone, we try to configure content in RichText like this:
![image](https://github.com/contentful/rich-text-renderer-java/assets/26249043/a2fa4e4d-ee68-47a7-a9d2-2aa081a239fc)

But as a result, we get content with extra spaces between link and dot.
![image](https://github.com/contentful/rich-text-renderer-java/assets/26249043/1393be10-651c-43ec-b0b8-287ebb06b69d)

Result html content in [html-with-extra-space.txt](https://github.com/contentful/rich-text-renderer-java/files/13296246/html-with-extra-space.txt)

As i understand, `TagRenderer` add new line after each tag and text, this is really necessary? What about cases like ours? In this case, the "new line" will be interpreted by the browser as a space.

**Comment by rafalniski** [comment]
Hey @IvanVoevodin are you on the `1.7.1` version? I recently added a fix for a similar case.

**Comment by IvanVoevodin** [comment]
Yes, i already upgrade it, but is fix the problem partially. Steel have space between link and point.
![image](https://github.com/contentful/rich-text-renderer-java/assets/26249043/23bc9be1-8a9e-4900-b19a-1ca9dcaff039)

**Comment by rafalniski** [comment]
And can you paste here the generated HTML, please?

**Comment by IvanVoevodin** [comment]
@rafalniski Yes, sure [rich-text-1.7.1-html.txt](https://github.com/contentful/rich-text-renderer-java/files/13512940/rich-text-1.7.1-html.txt)

**Comment by rafalniski** [comment]
Hey @IvanVoevodin, I created a fix for this in `2.0.0`. Please let me know if it works for you.
