### ISSUE TITLE
Maven import

### ISSUE THREAD

**Issue by matteo5883** [contentful/rich-text-renderer-java#5]
@mariobodemann I can't still import in my project the repository. #4

**Comment by mariobodemann** [comment]
Hey,

that is odd. Can you share your complete `pom.xml` or `build.gradle` file with me then? Additionally do you have any more sample to reproduce your issue?

Thanks,
Mario

**Comment by matteo5883** [comment]
this is my pom.xml file
[pom.txt.txt](https://github.com/contentful/rich-text-renderer.java/files/3094397/pom.txt.txt)

**Comment by vsthr** [comment]
Any updates on this? I am also not able to do an import...

**Comment by miron4dev** [comment]
Hello @matteo5883 

Jitpack doesn’t support repositories with a “dot” in the name, so Jitpack changes it to "~", which is not supported by Maven. 
https://github.com/jitpack/jitpack.io/issues/2372

This repo has been renamed from `rich-text-renderer.java` to `rich-text-renderer-java`
Changing the artifactId in your pom.xml should solve the problem.
