### ISSUE TITLE
Import passes, but no classes are found

### ISSUE THREAD

**Issue by quido3** [contentful/rich-text-renderer-java#9]
So I am currently trying to import the project. I am using Gradle imports and it was working for a while before the repository was renamed.

Currently the import happens without errors, but the 'com.contentful.rich' package is not found in class imports.

Gradle imports
`  implementation 'com.github.contentful.rich-text-renderer-java:all:master-SNAPSHOT'
    annotationProcessor 'com.contentful.vault:compiler:3.2.1'
    annotationProcessor 'com.contentful.vault:core:3.2.1'
    implementation 'com.contentful.vault:core:3.2.1'`

Class import
`import com.contentful.rich.android.AndroidProcessor;`

**Comment by HebbaniKavya** [comment]
I have the same issue as well. Is this going to be fixed any time soon-ish?

**Comment by rafalniski** [comment]
@quido3 @HebbaniKavya README.md file has been updated. Please try new instructions and let us know if that helps with the problem.

**Comment by rafalniski** [comment]
Please re-open when issue is still happening.
